version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: DfzKFU!5zGBA!
      POSTGRES_PASSWORD: "wm3q9JWEMY&QcW"
      POSTGRES_DB: ufeiradb
    ports:
      - "15432:5432"
    networks:
      - postgres-network      

networks: 
  postgres-network:
    driver: bridge